"""create_generated_projects_table

Revision ID: 4b914a14783a
Revises: b9587a69a1d5
Create Date: 2025-07-16 15:07:01.752954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b914a14783a'
down_revision = 'b9587a69a1d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###