"""add_project_generation_tables

Revision ID: b9587a69a1d5
Revises: ad1fd4b93f95
Create Date: 2025-07-16 00:33:18.584280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9587a69a1d5'
down_revision = 'ad1fd4b93f95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###