"""add_generated_projects_tables

Revision ID: d6344cf262d7
Revises: 4b914a14783a
Create Date: 2025-07-16 15:29:33.309262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6344cf262d7'
down_revision = '4b914a14783a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('title_template', sa.String(length=200), nullable=False),
    sa.Column('description_template', sa.Text(), nullable=False),
    sa.Column('required_skills', sa.JSON(), nullable=False),
    sa.Column('target_technologies', sa.JSON(), nullable=False),
    sa.Column('difficulty_levels', sa.JSON(), nullable=False),
    sa.Column('phases_template', sa.JSON(), nullable=False),
    sa.Column('deliverables_template', sa.JSON(), nullable=False),
    sa.Column('learning_objectives_template', sa.JSON(), nullable=False),
    sa.Column('estimated_duration_weeks', sa.Integer(), nullable=False),
    sa.Column('popularity_score', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_templates_id'), 'project_templates', ['id'], unique=False)
    op.create_table('generated_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_analysis_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False),
    sa.Column('target_skills', sa.JSON(), nullable=False),
    sa.Column('technologies_used', sa.JSON(), nullable=False),
    sa.Column('frameworks', sa.JSON(), nullable=True),
    sa.Column('databases', sa.JSON(), nullable=True),
    sa.Column('project_phases', sa.JSON(), nullable=False),
    sa.Column('deliverables', sa.JSON(), nullable=False),
    sa.Column('learning_objectives', sa.JSON(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('feasibility_score', sa.Float(), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('generation_method', sa.String(length=50), nullable=False),
    sa.Column('ai_model_used', sa.String(length=50), nullable=True),
    sa.Column('template_id', sa.String(length=100), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_analysis_id'], ['job_analyses.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_projects_id'), 'generated_projects', ['id'], unique=False)
    op.create_table('project_phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('phase_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=False),
    sa.Column('tasks', sa.JSON(), nullable=False),
    sa.Column('skills_practiced', sa.JSON(), nullable=False),
    sa.Column('deliverables', sa.JSON(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['generated_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_phases_id'), 'project_phases', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_phases_id'), table_name='project_phases')
    op.drop_table('project_phases')
    op.drop_index(op.f('ix_generated_projects_id'), table_name='generated_projects')
    op.drop_table('generated_projects')
    op.drop_index(op.f('ix_project_templates_id'), table_name='project_templates')
    op.drop_table('project_templates')
    # ### end Alembic commands ###